## githubiverse-template by Gary Hodgson
## license: GPL3
##
## The data below is left as an example.  Please change each entry to match your requirements. 
## 

## Uses distinct namespace. Jekyll settings should go at the root level.
Blendiverse:
    ## Metadata
    title: "Turtle"
    author: blendiverse
    license: GPL3
    tags: [mechanical movement, toy, arduino]

    ## Github project parameters.
    github:
	base: https://github.com/
        user: garyhodgson
        repository: githubiverse-tst
        branch: master


    ## The names of directories where any images, source and stl files associated with the project can be found.
    img_dir: stl_png
    stl_dir: stl
    src_dir: src

    ## The headline image
    lead_image: shell_front_left.stl
    show_lead_image: true

    ## Optional. When uncommented appends the content of the file defined here to the project description.  Any text in index.md, after the yaml header, will be shown first.
    description_file: README.md

    ## Preview the first STL in the list when the page loads.
    autoload_stl: true

    ## Show a github "fork me" ribbon in the top righthand corner of the page.
    show_forkme_ribbon: true